name = "openfuse-registry"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "REGISTRY"
bucket_name = "openfuse-registry"

routes = [
  { pattern = "registry.openfused.dev", custom_domain = true }
]

[vars]
CF_ZONE_ID = "dab75751e9235a8bd04665cb7772b726"
DNS_DOMAIN = "openfused.net"
